In [121]:
import numpy as np

In [122]:
c = np.array([[1,2,4],
              [6,5,4],
              [7,4,9]], dtype='int32')
print(c)
# get dimension
print(c.ndim)
# get shape
print(c.shape)
# get type
print(c.dtype)
# get size
print(c.itemsize)
print(c.nbytes)

[[1 2 4]
 [6 5 4]
 [7 4 9]]
2
(3, 3)
int32
4
36


In [123]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])

# get a specific element [r, c]
print(a[0,-1])
# get a specific row
print(a[0,:])
# get a specific column
print(a[:,2])
# get [row,startindex:endindex:stepsize]
print(a[0,1:6:2])
# change specific value
a[1,0] = -8
print(a)
a[:,2] = 0
print(a)
a[:,5] = [-1,-1]
print(a)

7
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [-8  9 10 11 12 13 14]]
[[ 1  2  0  4  5  6  7]
 [-8  9  0 11 12 13 14]]
[[ 1  2  0  4  5 -1  7]
 [-8  9  0 11 12 -1 14]]


In [55]:
b = np.array([
    [[1,2],
     [3,4]],
    
    [[5,6],
     [7,8]]
])

# get specific element (work outside in)
print(b[0,1,1])
print(b[:,1,:])
print('\n',b[:,:,1:])
# replace value
b[:,1,:] =  [[9,9],[8,8]]
print('\n',b)

4
[[3 4]
 [7 8]]

 [[[2]
  [4]]

 [[6]
  [8]]]

 [[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [67]:
# all zeros matrix
print('\n',np.zeros((3,3)))
# all ones matrix
print('\n',np.ones((3,3,3)))
# any other number
print('\n', np.full((2,2),1,dtype='float32'))
# any other number (full_like)
np.full(a.shape,4)


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

 [[1. 1.]
 [1. 1.]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
# random decimal numbers
print(np.random.rand(4,2))
print('\n', np.random.random_sample(a.shape))

[[0.27688009 0.95921169]
 [0.99142364 0.8568944 ]
 [0.60873699 0.58467159]
 [0.08264685 0.42245542]]

 [[0.15820794 0.89872295 0.77890243 0.96526107 0.52166868 0.94678492
  0.69831003]
 [0.17878069 0.82864784 0.57871899 0.58316395 0.36773567 0.86431098
  0.86081738]]


In [76]:
# random integer values
np.random.randint(4,8,size=(3,3))

array([[7, 6, 5],
       [7, 6, 6],
       [5, 6, 4]])

In [77]:
# the identity matrix - единичная матрица
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [84]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr,3,axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [87]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
# or
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [88]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [90]:
# correct way
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### Mathematics

In [93]:
a = np.array([1,2,3,4])
print(a - 2)
print(a * 2)
print(a / 2)

[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)
print(a**b)
print(np.cos(a))

[ 4 10 18]
[  1  32 729]
[ 0.54030231 -0.41614684 -0.9899925 ]


#### Linear Algebra

In [97]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [98]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [99]:
с = np.identity(3)
np.linalg.det(c)

-66.99999999999997

...

#### Statistics

In [105]:
stats = np.array([[1,2,3], [4,5,6]])
print(np.min(stats,axis=1))
print(np.max(stats,axis=1))

[1 4]
[3 6]


### Reorganizing arrays

In [106]:
before = np.array([[1,2,3,4],
                   [5,6,7,8]
                  ])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [109]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [110]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load data from file

In [111]:
np.genfromtxt('data.txt',delimiter=',')

OSError: data.txt not found.

In [113]:
t = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

t[t > 5]

array([6, 7, 8, 9])

In [116]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

##### Boolean masking and advanced indexing

In [118]:
np.any(t > 7,axis=0)

array([False,  True,  True])

In [119]:
np.all(t > 7,axis=0)

array([False, False, False])

In [120]:
(~((t>5) & (t < 10)))

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])