In [1]:
import numpy as np

## Базовая информация

#### В отличие от списков языка Python библиотека NumPy ограничевается массивами, содержащими элементы одного типа

In [5]:
ar = np.array([1, 2, 3, 4]) 

#### Если типы данных не совпадают, NumPy попытается выполнить повышающее приведение типов (в данном случае целовчисленные значения приводятся к числам с плавающей точкой)

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

#### Можно задать тип данных для элементов массива

In [2]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

## Создание массивов

#### Создаем массив целых чисел длины 10, заплненный нулями

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Создаем массив размером 3 x 5 значений с плавающей точкой, заполненный единицами

In [4]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Создаем массив размером 3 x 5, заполненный значением 3.14

In [5]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### Создаем массив, заполненный линейной последовательностью, начинающейся с 0 и заканчивающейся 20, с шагом 2 аналогично встроенной функции range()

In [15]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Создаем массив из пяти значений, равномерно располагающихся между 0 и 1

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Создаем массив размером 3 x 3 равномерно распределенных случайных значений от 0 до 1

In [7]:
np.random.random((3,3))

array([[0.44081953, 0.30011129, 0.01068541],
       [0.17147632, 0.78639246, 0.3510725 ],
       [0.11200804, 0.76696266, 0.25565744]])

#### Создаем массив размером 3 x 3 нормально распределенных случайных величин с медианой 0 и стандартным отклонением 1

In [8]:
np.random.normal(0, 1, (3, 3))

array([[ 0.55823132, -1.44984155, -0.4651683 ],
       [ 1.89749919,  0.27430666,  0.06817185],
       [ 0.73456004,  0.9067067 , -1.29427414]])

#### Создаем массив размером 3 x 3 случайных целых чисел в промежутке [0, 10)

In [9]:
np.random.randint(0, 10, (3,3))

array([[3, 8, 1],
       [6, 9, 8],
       [3, 9, 0]])

#### Создаем единичную матрицу размером 3 x 3

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Создаем неинициализированный массив из трех целочисленных значений. Значениями будут произвольные, случайно оказавшиеся в соответствующих ячейках памяти данные

In [11]:
np.empty(3) # Зачем оно нужно?

array([1., 1., 1.])

## Атрибуты массивов

#### Созданим 3 массива случайных чисел: одномерного, двумерного и трехмерного

In [12]:
# Задаем начальное значение SEED, чтобы гарантировать генерацию одних и тех же массивов при каждом выполнении кода 
np.random.seed(0)

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3,4)) # двумерный массив
x3 = np.random.randint(10, size=(3,4,5)) # трехмерный массив

#### У каждого из массивов есть атрибуты: 
- ndim - размерность
- shape - размер каждого измерения
- size - общий размер массива


- dtype - тип данных массива


- itemsize - размер каждого элемента массива в байтах
- nbytes - полный размер массива в байтах

In [13]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size, end='\n\n')

print("x3 dtype: ", x3.dtype, end='\n\n')

print(f"x3 itemsize: {x3.itemsize} bytes")
print(f"x3 nbytes: {x3.nbytes} bytes") # в общем равно size * itemsize

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60

x3 dtype:  int32

x3 itemsize: 4 bytes
x3 nbytes: 240 bytes


## Индексация массивов

#### В случае одномерного массива в NumPy все работает также как и в строенных списках Python

In [14]:
print("x1: ", x1)
print("Первый элемент массива: ", x1[0])
print("Четвертый элемент массива: ", x1[4])
print("Последний элемент массива: ", x1[-1])
print("Предпоследний элемент массива: ", x1[-2])

x1:  [5 0 3 3 7 9]
Первый элемент массива:  5
Четвертый элемент массива:  7
Последний элемент массива:  9
Предпоследний элемент массива:  7


#### Обращаться к элементам в многомерных массивах можно с помощью разделенных запятыми кортежей индексов:

In [15]:
print(x2, end="\n\n")
print("Первый элемент, первой строки массива: ", x2[0, 0])
print("Первый элемент, третьей строки массива: ", x2[2, 0])
print("Последний элемент, третьей строки массива: ", x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

Первый элемент, первой строки массива:  3
Первый элемент, третьей строки массива:  1
Последний элемент, третьей строки массива:  7


#### Таким же способом можно изменить значение элемента в массиве

In [16]:
x2[2, -1] = 6
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 6]])

#### Помните про фиксированный тип данных массива. При попытке вставить в массив целых чисел значение с плавающей точкой это значение будет учечено

In [17]:
print(x1)
x1[0] = 3.14159
print(x1)

[5 0 3 3 7 9]
[3 0 3 3 7 9]


## Срезы массивов

### Доступ к подмассивам

#### Синтаксис срезов библиотеки NumPy соответствует аналогичному синтаксису для страндартных списков языка Python. Для доступа к срезу массива x используется синтаксис:
#### [начало: конец: шаг]
#### Если какие-либо из этих значений не указаны, значения применяются по умолчанию:
- начало = 0
- конец = размер соответствующего измерения
- шаг = 1

In [62]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
print("Первые пять элементов массива: ", x[:5])
print("Элементы после индекса = 5: ", x[5:])
print("Подмассив из середины: ", x[4:7])
print("Каждый второй элемент: ", x[::2])
print("Каждый второй элемент, начиная с индекса 1: ", x[1::2])

Первые пять элементов массива:  [0 1 2 3 4]
Элементы после индекса = 5:  [5 6 7 8 9]
Подмассив из середины:  [4 5 6]
Каждый второй элемент:  [0 2 4 6 8]
Каждый второй элемент, начиная с индекса 1:  [1 3 5 7 9]


##### Отрицательное значение параметра "шаг" может запутать. В этом случае значения по умалчанию для "начало" и "конец" меняются местами. Это удобный способ перевернуть массив

In [68]:
print("Массив x: ", x)
print("Все элементы в обратном порядке: ", x[::-1])
print("Каждый второй элемент в обратном порядке, начиная с индекса 5: ", x[5::-2])

Массив x:  [0 1 2 3 4 5 6 7 8 9]
Все элементы в обратном порядке:  [9 8 7 6 5 4 3 2 1 0]
Каждый второй элемент в обратном порядке, начиная с индекса 5:  [5 3 1]


### Многомерные подмассивы

#### Многомерные срезы задаются схожим образом, с разделением срезов запятыми

In [72]:
print(x2, end='\n\n')
print("Две строки, три столбца: \n", x2[:2, :3], end='\n\n')
print("Все строки, каждый второй столбец: \n", x2[:3, ::2], end='\n\n')

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 6]]

Две строки, три столбца: 
 [[3 5 2]
 [7 6 8]]

Все строки, каждый второй столбец: 
 [[3 2]
 [7 8]
 [1 7]]



##### Измерения подмассивов также можно переворачивать:

In [73]:
x2[::-1, ::-1]

array([[6, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

##### При этом срезы массивов являются представлениеми (views), а не копиями (copies) данных изначального массива. Тоесть...

In [77]:
# Если мы извлечем из массива подмассив подмассив...
print("Изначальный массив: \n\n", x2, end="\n\n")
x2_sub = x2[:2, :2]
print("Подмассив: \n\n", x2_sub)

Изначальный массив: 

 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 6]]

Подмассив: 

 [[3 5]
 [7 6]]


In [80]:
# ...То изменение подмасива также изменит изначальный массив
x2_sub[0, 0] = 99
print("Измененный подмассив: \n\n", x2_sub, end='\n\n')
print("Изначальный подмассив: \n\n", x2, end='\n\n')

Измененный подмассив: 

 [[99  5]
 [ 7  6]]

Изначальный подмассив: 

 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  6]]



##### Таким образом, при работе с большими наборами данных не требуется копировать базовый буфер данных для обращения к их частям и обработки этих частей

##### Но если нужно явным образом скопировать данные из массива или подмассива, это легко можно сделать с помощью метода copy:

In [85]:
print("Изначальный массив: \n\n", x2, end='\n\n')

x2_sub_copy = x2[:2, :2].copy()
print("Копия среза массива: \n\n", x2_sub_copy, end='\n\n')

x2_sub_copy[0, 0] = 42
print("Измененная копия среза: \n\n", x2_sub_copy, end='\n\n')

print("Изначальный массив: \n\n", x2)

Изначальный массив: 

 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  6]]

Копия среза массива: 

 [[99  5]
 [ 7  6]]

Измененная копия среза: 

 [[42  5]
 [ 7  6]]

Изначальный массив: 

 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  6]]


### Изменение формы массивов

##### Если вам, например, требуется поместить числа от 1 до 9 в таблицу 3 x 3, сделать это можно следующим образом:

In [18]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### При этом размер (size) исходного массива должен соответствовать размеру измененного

##### Часто используемый паттерн изменения формы  - преобразование одномерного массива в двумерную матрицу-строку или матрицу-столбец. Для этого можно воспользоваться методом reshape, но лучше воспользоваться ключевым словом newaxis при выпольнении опреации среза

In [19]:
x = np.array([1,2,3])
print("Изначальный массив: ", x)
print("Преобразование в вектор-строку с помощью reshape: ", x.reshape((1,3)))
print("Преобразование в вектор-строку с помощью newaxis: ", x[np.newaxis,:], end= '\n\n')

print("Преобразование в вектор-столбец с помощью reshape: \n\n", x.reshape((3,1)), end='\n\n')
print("Преобразование в вектор-столбец с помощью newaxis: \n\n", x[:, np.newaxis], end='\n\n')

Изначальный массив:  [1 2 3]
Преобразование в вектор-строку с помощью reshape:  [[1 2 3]]
Преобразование в вектор-строку с помощью newaxis:  [[1 2 3]]

Преобразование в вектор-столбец с помощью reshape: 

 [[1]
 [2]
 [3]]

Преобразование в вектор-столбец с помощью newaxis: 

 [[1]
 [2]
 [3]]



##### Все предыдущие операции работали с одним массивом. Но можно объединить несколько массивов в один и, наоборот, разбить единый массив на несколько подмассивов

### Слияние массивов

##### Слияние, или объединение, двух массивов выполняется, в основном, с помощью метожов:
- np.concatenate
- np.vstack
- np.hstack

np.concatenate

In [20]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

##### Можно объединить более двух массивов одновременно

In [21]:
z = [99, 99, 99]

np.concatenate([x, y, z]) 

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

##### Для объединения двумерных массивов также использовать np.concatinate

In [22]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

In [23]:
np.concatenate([grid, grid]) # слияние по первой оси координат

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([grid, grid], axis=1) # слияние по второй оси координат (с интексом 0)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

##### Для работы с массивами с различающимися измерениями удобно использовать функции np.vstack (вертикальное объединение) и np.hstack (горизонтальное объединение)

np.vstack

In [25]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], 
                 [6,5,4]])

In [26]:
np.vstack([x, grid]) # объединение массивов по вертикали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

np.hstack

In [27]:
np.vstack([x, grid]) # объединение массивов по горизонтали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

##### Функция np.dstack аналогично объединяет массивы по третьей оси

### Разбиение массивов

###### Противоположностью слияния является разбиение, выполняемой с помощью функций:
- np.split
- np.hsplit
- np.vsplit

###### Каждой из них необходимо передавать список индексов, задаюзих точки раздела

np.split

In [28]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


##### Обратите внимание, что N точек раздела означают N + 1 подмассив. Функции np.hsplit и np.vsplit действуют аналогично

In [29]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
upper, lower = np.vsplit(grid, [2])

print(upper, end='\n\n')
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


np.hsplit

In [31]:
left, right = np.hsplit(grid, [2])

print(left, end='\n\n')
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##### Функция np.dsplit аналогично разделяет массивы по третьей оси